### ISSUE TITLE
raycast error

### ISSUE THREAD

**Issue by rmrbytes** [omgitsraven/aframe-room-component#1]
Hello,

While using the room-component, I see a JS console error as follows, even though the rooms do showup.

three.js:15179 Uncaught TypeError: Cannot read property 'count' of undefined
    at Lt.Object.assign.raycast (three.js:15179)
    at Xn (three.js:39252)
    at Xn (three.js:39260)
    at jn.intersectObjects (three.js:39329)
    at i.tick (raycaster.js:165)
    at a-scene.js:517
    at Array.forEach (<anonymous>)
    at HTMLElement.value (a-scene.js:515)
    at HTMLElement.value (a-scene.js:562)
    at HTMLElement.render (bind.js:12)

**Comment by omgitsraven** [comment]
Hi,

It's hard to say where this is going wrong, none of those lines are inside my code (although it could still be due to my code if I've put something malformed into the scene). Is there somewhere I can view a copy of the scene to isolate what causes it?

**Comment by rmrbytes** [comment]
Meanwhile, I made a few changes and I do not see the error any more. The only changes I seem to have made is: changing the aframe lib from 0.6.0 to 0.6.1.

Thanks and I look forward to more features being added. Its a big relief to have this module.

**Comment by omgitsraven** [comment]
Alright :) I would still like to see an example where 0.6.0 causes a problem though, in case it's something I can resolve for other users... I originally developed against 0.6.1, and only fixed it to work with 0.6.0 at the end, so it's possible I've missed things.

Anyway good luck with your project, I'm glad to be able to help :)

**Comment by rmrbytes** [comment]
I have not been able to reproduce the error even with a 0.6.0 change and when I think back I am not sure what other change I made. Perhaps, it was something else.

Just curious, is there a road map you have in place for this module? Windows, Doors (swivel), lights etc

**Comment by omgitsraven** [comment]
Doors will not be a part of this specific module -- something like that is a general feature, that could be useful with imported models of buildings for example, and so it should be made separately. (I might make it myself, but probably not -- it would be far down the roadmap for me because it's a more general task that someone else could do.)

As I mentioned in the readme, windows are planned, but probably only after a few other features... It wouldn't be difficult to add, but I'm a bit busy at the moment, so I can't promise how soon it'll be. I can bump it up in priority if you think it would be more useful than things like building exteriors.

Lights are part of A-Frame already, that's already available and has nothing to do with me. You can place a lamp model (and a light source inside it) just by parenting it to the wall, or the ceiling, or the room. My module is just for making the structure of the rooms; you fill the rooms with normal A-Frame elements.

**Comment by rmrbytes** [comment]
Thanks for the update. Will revert to you in case of any challenges. Am creating an educational VR room with multiple students (networked scene). Lets see how that goes.
